language: ruby
script: bundle exec rake spec
rvm:
  - ruby-2.1.6
  - ruby-2.2.3
notifications:
  email:
    recipients:
      - drnicwilliams@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    - secure: ""
