language: ruby
script: bundle exec rake spec
rvm:
  - ruby-2.2.5
notifications:
  email:
    recipients:
      - drnicwilliams@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    - secure: ""
